//
//  deneme.swift
//  sporApp
//
//  Created by Eyüphan Akkaya on 26.06.2023.
//

import Foundation

class AltBaslikEklendi{
    let a1 = AltBaslik(id: 1, ad: "Bench Press", resim: "", kategori_id: 1,aciklama: "Lorem ipsum dolor sit er elit lamet, consectetaur cillium adipisicing pecu, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Nam liber te conscient to factor tum poen legum odioque civiuda.",ytId: "rT7DgCr-3pg")
    let a2 = AltBaslik(id: 2, ad: "Squat", resim: "", kategori_id: 1,aciklama: "uzun metin",ytId: "SW_C1A-rejs")
    let a3 = AltBaslik(id: 3, ad: "Incline Bench Press", resim: "", kategori_id: 1,aciklama: "Lorem ipsum dolor sit er elit lamet, consectetaur cillium adipisicing pecu, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Nam liber te conscient to factor tum poen legum odioque civiuda.",ytId: "SrqOu55lrYU")
    let a4 = AltBaslik(id: 4, ad: "Over head Press", resim: "", kategori_id: 1,aciklama: "Lorem ipsum dolor sit er elit lamet, consectetaur cillium adipisicing pecu, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Nam liber te conscient to factor tum poen legum odioque civiuda.",ytId: "Vyt2QdsR7E")
    let a5 = AltBaslik(id: 5, ad: "Deadlift", resim: "", kategori_id: 1,aciklama: "",ytId: "JCXUYuzwNrM")
    let a6 = AltBaslik(id: 6, ad: "Plank Prep Exercise", resim: "", kategori_id: 2,aciklama: "Daha çok bacak, sırt ve karın kaslarını esnetmek ve güçlendirmek için kullanılan bir tür ısınma hareketi olarak düşünülebilir. Kıvrılma manevrası, omurgayı ve karın kaslarını daha zorlu egzersizler için hazır hale getirmeye başlarken, kaldırma (lifting) ise bacak ve kalça kaslarını kuvvetlendirmeyi amaçlar.",ytId: "vUIVMQnSpH8")
    let a7 = AltBaslik(id: 7, ad: "Hundred", resim: "", kategori_id: 2,aciklama: "Hundred, kaburgaları genişleterek nefes alıp verişlerinizin daha düzenli hale gelmesini sağlar. Merkez bölgesinin (Core) önemli kasları özellikle de en derin katmanı oluşturan çapraz kasları (external obliques) geliştirir. Hundred, bacaklarınızı ters yönde esnetirken omurganızın üst tarafının yukarı ve ileri yönde kıvrılmasıyla omurganızı güçlendirir ve uzatır.",ytId: "On2BPeK4q2Y")
    
    let a8 = AltBaslik(id: 8, ad: "One Leg Circle", resim: "", kategori_id: 2,aciklama: "Bu pilates hareketi, bedenin merkez (core) bölgesini güçlendirmeyi amaçlayan bir tekniktir. Kurallarına dikkat edilerek yapılırsa, bacak kaslarınızın uzayarak, abdominal kaslarla birlikte daha da güçlendiğini rahatlıkla hissedebilirsiniz. Her bir bacak için 8-10 kere daire çizme hareketi yapabilirsiniz.",ytId: "zeUW8LFUEPo")
    
    let a9 = AltBaslik(id: 9, ad: "Single Leg Stretch ", resim: "", kategori_id: 2,aciklama: "Single Leg Stretch olarak bilinen tek bacak esnetme hareketi, karın kaslarını sıkılaştırır. Bu teknik, ilk hareketi abdominal kaslardan alarak bedeni eğitir; vücut yalnızca kollar ve bacaklar hareket ettiğinden sabit kalarak en iyi şekilde desteklenmeye zorlanır. Bu egzersiz tüm beden için dayanıklılık ve koordinasyon arttırıcı bir çalışmadır.",ytId: "woYtwok_YUQ")
    
    let a10 = AltBaslik(id: 10, ad: "Side Leg Lift ", resim: "", kategori_id: 2,aciklama: "Yan yatarak tek bacağınızı yukarı kaldırma hareketi, kalça, karın kasları ve bacakları çalıştırır.",ytId: "cFkdGI75SMA&t=1s")
    let a11 = AltBaslik(id: 11, ad: "Beats Exercise ", resim: "", kategori_id: 2,aciklama: "Köprü hareketi, omurgayı esnetir, gluteus kasının (kalça kası) yanında hamstring kasını da (üst arka bacak kası) etkili bir şekilde çalıştırır. Bu çalışma omurlar arası bağlantıyı çalıştırır, omurgayı hareketlendirir ve pelvisin çalışmasını sağlar. Bel fıtığı rahatsızlığında da önerilen hareketlerdendir.",ytId: "eZMTNEQKIWE")
    let a12 = AltBaslik(id: 12, ad: "Spine Twist", resim: "", kategori_id: 2,aciklama: "Bu pilates hareketi, omurgamızı esneten ve güçlendiren egzersizlerinden birisidir. Bu egzersiz, sakatlıklardan daha az etkilenmeyi sağlayacak şekilde, omurga ve gövdenin hareket kabiliyeti aralığını arttırır. Hareket boyunca pelvisin sabit olarak tutulması gerekir. Ayrıca bu teknik yardımıyla duruşunuz daha iyi bir seviyeye getirilebilir. Tüm beden için koordinasyonu ve stabiliteyi olumlu anlamda geliştiren çalışmalardandır.",ytId: "hYsRIAC9ixM")
    let a13 = AltBaslik(id: 13, ad: "Single Leg Kick", resim: "", kategori_id: 2,aciklama: "Bu pilates hareketi, vücudun arka kısmını, kalça ve basenleri, arka bacak kas gruplarını ve omurgayı çalıştıran bir çalışmadır. Bu teknik yardımı ile arka bacak ve kalça bölgesi şekil alıp sıkılaşırken, aynı zamanda bacakların ön kısmı ile kalça fleksör kaslarının uzatılması da kolaylaşmaktadır. Üst beden ağırlığının ön kol bölgesine verilmesi, biseps ve triseps kaslarının dayanıklılığını arttırırken, kolların yukarı kısımlarının şekillendirilmesi konusunda da olumlu etkilere sahiptir.",ytId: "woYtwok_YUQ")
    let a14 = AltBaslik(id: 14, ad: "Inner Thigh Leg Lift", resim: "", kategori_id: 2,aciklama: "Bu pilates hareketi, iç bacağın yanında karın kasları ve kalçayı da çalıştıran bir egzersizdir.",ytId: "cFkdGI75SMA")
    let a15 = AltBaslik(id: 15, ad: "Mermaid ", resim: "", kategori_id: 2,aciklama: "Deniz Kızı hareketi, omurgaya hareketlilik kazandırırken, yan karın kaslarının da çalışmasını sağlayan mükemmel hareketlerden biridir.",ytId: "iEUBi98L16M")
}
